fix : git action & type Err

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -160,16 +160,26 @@ jobs:
         working-directory: ./front
         run: npm run build
 
-      - name: Delete src folder
-        working-directory: ./front
-        run: |
-          if [ -d "src" ]; then rm -rf src; fi
-
       - name: Copy Files to EC2
         run: |
           ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
             mkdir /var/www/threeOpenAi/front'
-          rsync -avz -e "ssh" ./front/ ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/front
+          rsync -avz -e "ssh" ./front/.next ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/front
+          rsync -avz -e "ssh" ./front/public ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/front
+          rsync -avz -e "ssh" ./front/package.json ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/front
+
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else
+              echo "nvm.sh not found"
+              exit 1
+            fi
+
+            nvm use --lts
+            cd /var/www/threeOpenAi/front
+            npm i --production'
 
   deploy_back:
     runs-on: ubuntu-latest
@@ -208,16 +218,26 @@ jobs:
         working-directory: ./back
         run: npm run build
 
-      - name: Delete src folder
-        working-directory: ./back
-        run: |
-          if [ -d "src" ]; then rm -rf src; fi
-
       - name: Copy Files to EC2
         run: |
           ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
             mkdir /var/www/threeOpenAi/back'
-          rsync -avz -e "ssh" ./back/ ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/back
+          rsync -avz -e "ssh" ./back/dist ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/back
+          rsync -avz -e "ssh" ./back/.env ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/back
+          rsync -avz -e "ssh" ./back/package.json ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/back
+
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else
+              echo "nvm.sh not found"
+              exit 1
+            fi
+
+            nvm use --lts
+            cd /var/www/threeOpenAi/back
+            npm i --production'
 
   restart_nginx:
     runs-on: ubuntu-latest
