git try

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -160,21 +160,26 @@ jobs:
         working-directory: ./front
         run: npm run build
 
-      - name: reInstall
-        working-directory: ./front
-        run: |
-          if [ -d "node_modules" ]; then rm -rf node_modules; fi
-          npm i --production
-
       - name: Copy Files to EC2
         run: |
           ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
             mkdir /var/www/threeOpenAi/front'
           rsync -avz -e "ssh" ./front/.next ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/front
           rsync -avz -e "ssh" ./front/public ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/front
-          rsync -avz -e "ssh" ./front/package-lock.json ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/front
           rsync -avz -e "ssh" ./front/package.json ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/front
-          rsync -avz -e "ssh" ./front/node_modules ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/front
+
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else
+              echo "nvm.sh not found"
+              exit 1
+            fi
+
+            nvm use --lts
+            cd /var/www/threeOpenAi/front
+            npm i --production'
 
   deploy_back:
     runs-on: ubuntu-latest
@@ -214,21 +219,26 @@ jobs:
         working-directory: ./back
         run: npm run build
 
-      - name: reInstall
-        working-directory: ./back
-        run: |
-          if [ -d "node_modules" ]; then rm -rf node_modules; fi
-          npm i --production
-
       - name: Copy Files to EC2
         run: |
           ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
             mkdir /var/www/threeOpenAi/back'
           rsync -avz -e "ssh" ./back/dist ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/back
           rsync -avz -e "ssh" ./back/.env ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/back
-          rsync -avz -e "ssh" ./back/package-lock.json ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/back
           rsync -avz -e "ssh" ./back/package.json ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/back
-          rsync -avz -e "ssh" ./back/node_modules ${{ secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/threeOpenAi/back
+
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else
+              echo "nvm.sh not found"
+              exit 1
+            fi
+
+            nvm use --lts
+            cd /var/www/threeOpenAi/back
+            npm i --production'
 
   restart_nginx:
     runs-on: ubuntu-latest
